BaSP-TG-08: Super admin
BaSP-a2022/lucas-a-trackgenix-server pull request #11
Opened 2022-10-15 22:11 UTC by TomasBettini

2022-10-15 23:24 UTC, lmalvasia commented on src/controllers/super-admins.js
> +    const superAdmins = await SuperAdmins.find();
use the query params here to filter the data

2022-10-15 23:24 UTC, lmalvasia commented on src/controllers/super-admins.js
> +    const superAdmin = await SuperAdmins.findById(idNumber);
```suggestion
    const superAdmin = await SuperAdmins.findById(req.params.id);
```

2022-10-15 23:24 UTC, lmalvasia commented on src/controllers/super-admins.js
> +    const idNumber = req.params.id;
remove this line

2022-10-15 23:24 UTC, lmalvasia commented on src/controllers/super-admins.js
> +    const superAdmin = await SuperAdmins.findById(idNumber);
the findById function could return an undefined value when we send an invalid id, so you have to add an extra validation to check this and to make a different response in this case.

2022-10-15 23:24 UTC, lmalvasia commented on src/controllers/super-admins.js
> +export default {
remove the export default and export each function individually.

2022-10-15 23:24 UTC, lmalvasia commented on src/index.js
> +const port = 4000;
Why you change the port? We should use always the same port and this change could affect the other guys.

2022-10-15 23:24 UTC, lmalvasia commented on src/validations/super-admins.js
> +const validateCreation = (req, res, next) => {
```suggestion
const validateSuperAdminBody = (req, res, next) => {
```

2022-10-15 23:24 UTC, lmalvasia commented on src/validations/super-admins.js
> +export default {
export default validateSuperAdminBody;

2022-10-16 18:41 UTC, TomasBettini commented on src/controllers/super-admins.js
> +    const idNumber = req.params.id;
I don't understand which is the line that I should remove

2022-10-16 18:42 UTC, TomasBettini commented on src/index.js
> +const port = 4000;
My colleagues and I had to change the port because the server was not working for us

2022-10-16 19:17 UTC, leimeter-joaquin requested changes

2022-10-16 19:17 UTC, leimeter-joaquin commented on src/validations/super-admins.js
> +const validateCreation = (req, res, next) => {
Why is this marked as resolved?

2022-10-16 19:17 UTC, leimeter-joaquin commented on src/validations/super-admins.js
> +export default {
This one as well

2022-10-16 19:17 UTC, leimeter-joaquin commented on src/controllers/super-admins.js
> +    const idNumber = req.params.id;
It´s line 22 and follow the suggestion in line 23.

2022-10-16 19:20 UTC, TomasBettini commented on src/validations/super-admins.js
> +const validateCreation = (req, res, next) => {
Because I haven't pushed it yet to do it in a commit but in my code I corrected it

2022-10-16 19:21 UTC, TomasBettini commented on src/validations/super-admins.js
> +export default {
Same as the other comments marked as resolved

2022-10-16 19:27 UTC, leimeter-joaquin commented on src/controllers/super-admins.js
> +    const superAdmins = await SuperAdmins.find();
@TomasBettini Check how mongoose facilitates this process.

2022-10-16 23:56 UTC, lmalvasia approved these changes

2022-10-17 00:09 UTC, leimeter-joaquin approved these changes

2022-10-17 00:26 UTC, merged