BaSP-TG-10:Task
BaSP-a2022/lucas-a-trackgenix-server pull request #12
Opened 2022-10-15 22:26 UTC by julianpiaggio

2022-10-16 20:04 UTC, leimeter-joaquin requested changes
Please add the changes to the  postman collection

2022-10-17 18:54 UTC, leimeter-joaquin requested changes

2022-10-17 18:54 UTC, leimeter-joaquin commented on src/controllers/tasks.js
> +export default {
Don't export default, export every function individually.

2022-10-17 18:54 UTC, leimeter-joaquin commented on src/routes/tasks.js
> +import taskControllers from '../controllers/tasks';
```suggestion
import { getAllTasks, getTasksById, createTask } from '../controllers/tasks';
```

2022-10-17 19:17 UTC, leimeter-joaquin submitted a review, later dismissed

2022-10-17 20:34 UTC, kolodani approved these changes
great work, ready to merge

2022-10-17 20:34 UTC, merged