BaSP-TG-04: admins
BaSP-a2022/lucas-a-trackgenix-server pull request #14
Opened 2022-10-15 23:44 UTC by kolodani

2022-10-16 23:26 UTC, leimeter-joaquin requested changes

2022-10-16 23:33 UTC, lmalvasia commented on src/controllers/admins.js
> +    const admins = await Admins.find();
It's not necessary to add a validation here. We have to filter the data based on the query params.
```suggestion
    const admins = await Admins.find(req.query);
```

2022-10-16 23:34 UTC, lmalvasia commented on src/controllers/admins.js
> +    const admin = await Admins.findById(id);
This is correct. We have to add an extra validation here because the method findById could return an undefined value. If the `admin` is undefined, we have to change the response.

2022-10-16 23:35 UTC, lmalvasia commented on src/controllers/admins.js
>  // DELETE AN ADMIN
I think he commented the following functions because he deleted the `fs`.

2022-10-16 23:36 UTC, lmalvasia commented on src/controllers/admins.js
> +export default {
Don't use the export default here. We have to export each function individually.

2022-10-16 23:36 UTC, lmalvasia commented on src/validations/admins.js
> +const validateCreation = (req, res, next) => {
```suggestion
const validateAdminBody = (req, res, next) => {
```

2022-10-16 23:36 UTC, lmalvasia commented on src/validations/admins.js
> +export default {
```suggestion
export default validateAdminBody;
```

2022-10-16 23:39 UTC, kolodani commented on package-lock.json
> +        "node": ">14.x"
the change is done automatically

2022-10-17 00:09 UTC, kolodani commented on src/controllers/admins.js
> +    const admin = await Admins.findById(id);
Resolved

2022-10-17 00:09 UTC, kolodani commented on src/controllers/admins.js
> +    const admins = await Admins.find();
Resolved

2022-10-17 00:09 UTC, kolodani commented on src/validations/admins.js
> +const validateCreation = (req, res, next) => {
resolved

2022-10-17 00:09 UTC, kolodani commented on src/validations/admins.js
> +export default {
resolved

2022-10-17 00:12 UTC, leimeter-joaquin requested changes

2022-10-17 00:12 UTC, leimeter-joaquin commented on src/controllers/admins.js
> +      error: false,
@lmalvasia Shouldn't this be `error: true`?

2022-10-17 00:12 UTC, leimeter-joaquin commented on src/controllers/admins.js
> +      error: error.message,
the error should be true and the message should have the error.message

2022-10-17 00:12 UTC, leimeter-joaquin commented on src/controllers/admins.js
> +      error: false,
Same on line 31

2022-10-17 00:19 UTC, kolodani commented on src/controllers/admins.js
> +      error: false,
resolved

2022-10-17 00:19 UTC, kolodani commented on src/controllers/admins.js
> +      error: error.message,
resolved

2022-10-17 02:09 UTC, leimeter-joaquin requested changes

2022-10-17 02:09 UTC, leimeter-joaquin commented on src/controllers/admins.js
> +        error: false,
this error should be true as well

2022-10-17 02:19 UTC, kolodani commented on src/controllers/admins.js
> +        error: false,
change add

2022-10-17 13:31 UTC, leimeter-joaquin submitted a review, later dismissed

2022-10-17 13:52 UTC, matescarabino approved these changes
Todo OK

2022-10-17 13:52 UTC, merged