BaSP-TG: Time sheet functions
BaSP-a2022/lucas-a-trackgenix-server pull request #2
Opened 2022-10-10 13:52 UTC by Valentin-sanabria

- Create timesheet
- Edit timesheet
- Delete timesheet
- Get specific timesheet
- Get all timesheets
- Filter all timesheets

2022-10-10 15:17 UTC, leimeter-joaquin requested changes

2022-10-10 17:00 UTC, kolodani reviewed
vi un cartel que estaba mal valen que era el que hablamos por discord

2022-10-10 17:00 UTC, kolodani commented on src/resources/time-sheets.js
> +      res.send('Created New Project');
el cartel de aca no coincide con el delete

2022-10-10 17:27 UTC, leimeter-joaquin requested changes
Check this for every `fs.writeFile` in the file please

2022-10-10 17:27 UTC, leimeter-joaquin commented on src/resources/time-sheets.js
> +      res.send('Created New Project');
Yes, the message should not indicate that a proyect has been created. Be careful when copying logic form another file.

Check if this logic is correct. You are sending a success message when Json.stringify HAS an error

2022-10-11 14:20 UTC, leimeter-joaquin commented on src/resources/time-sheets.js
> +        res.send('Cannot create new Project');
Is there a reason you are usingn "new Project" here? If not, please change this text.

2022-10-12 00:21 UTC, JuliBalcaza approved these changes
Great job Valen!

2022-10-12 00:23 UTC, JuliBalcaza approved these changes

2022-10-12 00:25 UTC, JuliBalcaza approved these changes

2022-10-12 00:36 UTC, leimeter-joaquin approved these changes

2022-10-12 00:37 UTC, merged