BaSP-TG-W08: admin
BaSP-a2022/lucas-a-trackgenix-server pull request #3
Opened 2022-10-10 15:03 UTC by mara666

2022-10-10 17:04 UTC, kolodani reviewed
muy buen codigo dario, fijate que los comentarios antes de las funciones no se si siguen siendo tan necesarios, porque el codigo ahora es muy claro y el nombre de las funciones dan a entender todo

2022-10-10 17:22 UTC, leimeter-joaquin requested changes

2022-10-10 17:22 UTC, leimeter-joaquin commented on src/resources/admins.js
> +const filterAdmin = (req, res) => {
Filters need validation

2022-10-10 17:33 UTC, leimeter-joaquin requested changes

2022-10-10 17:33 UTC, leimeter-joaquin commented on src/resources/admins.js
> +  }
You should validate the id of the created admin for duplicates.

2022-10-10 17:33 UTC, leimeter-joaquin commented on src/resources/admins.js
> +    res.status(400).json({ msg: `Cannot delete Admin with id ${req.params.id}, because it doesent exist!` });
typo here at doesent

2022-10-11 14:25 UTC, leimeter-joaquin requested changes

2022-10-11 14:25 UTC, leimeter-joaquin commented on src/resources/admins.js
> +    res.status(400).json({ msg: `Cannot delete Admin with id ${req.params.id}, because it doesent exist!` });
Text should be: `Cannot delete Admin with id ${req.params.id}, because it doesn't exist!`

2022-10-11 14:25 UTC, leimeter-joaquin commented on src/resources/admins.js
> +const filterAdmin = (req, res) => {
You should validate that the params are correct or not.
Example:
```
  // Checking that the user usese the correct filter params.
  queriesArray.forEach((query) => {
    if (query !== 'id' && query !== 'startDate' && query !== 'endDate') {
      res.status(400).json({
        message: 'Some filter parameter is not valid',
      });
    }
  });
```

2022-10-11 18:08 UTC, leimeter-joaquin approved these changes

2022-10-11 18:22 UTC, leimeter-joaquin approved these changes

2022-10-11 18:25 UTC, merged