BaSP-TG-21: Time-sheets-tests
BaSP-a2022/lucas-a-trackgenix-server pull request #33
Opened 2022-10-23 23:48 UTC by mara666

2022-10-24 22:41 UTC, lmalvasia commented on package.json
> +    "test": "jest --verbose",
Is this necessary? Why did you add this?

2022-10-24 22:41 UTC, lmalvasia commented on src/tests/time-sheets.test.js
> +  describe('GET BY ID ERROR /:id', () => {
Move all the tests inside only one describe (we should have only one per method)

2022-10-24 22:41 UTC, lmalvasia commented on src/tests/time-sheets.test.js
> +    test('should return status code 400', async () => {
Why the request is returning a status 40?
You have to add the purpose why this is going to return an error.
```suggestion
    test('should return status code 400 when the id is invalid', async () => {
```

2022-10-24 22:41 UTC, lmalvasia commented on src/tests/time-sheets.test.js
> +      expect(response.body.message).toBe(`${response.body.message}`);
This equal to have expect(true).toBe(true). It's wrong.
You should have something like:
```suggestion
      expect(response.body.message).toEqual(`Invalid Id`);
```

2022-10-24 22:41 UTC, lmalvasia commented on src/tests/time-sheets.test.js
> +    test('should return status code 400', async () => {
Why the request is returning a status 400?
You have to add the purpose why this is going to return an error.

2022-10-24 22:41 UTC, lmalvasia commented on src/tests/time-sheets.test.js
> +      expect(response.body.message).toBe(`${response.body.message}`);
This is wrong.

2022-10-24 22:41 UTC, lmalvasia commented on src/tests/time-sheets.test.js
> +      expect(response.body.message).toBe(`${response.body.message}`);
This is wrong.

2022-10-24 22:59 UTC, leimeter-joaquin requested changes

2022-10-24 22:59 UTC, leimeter-joaquin commented on src/tests/time-sheets.test.js
> +      expect(response.body.error).toBeFalsy();
The error property is either true or false, probably best to use `.toBe(false)` I believe we want it to be false, not undefined or null or '' or 0, for example

2022-10-24 22:59 UTC, leimeter-joaquin commented on src/tests/time-sheets.test.js
> +      expect(response.body.error).toBeTruthy();
Same here as in my last comment

2022-10-24 22:59 UTC, leimeter-joaquin commented on src/tests/time-sheets.test.js
> +      expect(response.body.error).toBeTruthy();
Well, with true, of course

2022-10-24 22:59 UTC, leimeter-joaquin commented on src/tests/time-sheets.test.js
> +      expect(response.body.error).toBeFalsy();
Same here

2022-10-25 02:03 UTC, mara666 commented on package.json
> +    "test": "jest --verbose",
I use this because in console doesn't show the describes!

2022-10-25 12:46 UTC, lmalvasia commented on src/tests/time-sheets.test.js
> +    });
Add a new line between each test to separate them
For example
```
    test('should not create a project when there is not body', async () => {
       ....
    });

    test('should not create a project when the user send an invalid project name', async () => {
      ....
    });
```

2022-10-25 13:07 UTC, leimeter-joaquin approved these changes

2022-10-25 13:17 UTC, kolodani submitted a review, later dismissed
awesome coworker

2022-10-25 13:24 UTC, kolodani approved these changes
all fix

2022-10-25 13:24 UTC, merged