Feature/tg w08/employee
BaSP-a2022/lucas-a-trackgenix-server pull request #5
Opened 2022-10-10 16:14 UTC by kolodani

end my part of the proyect

2022-10-10 17:41 UTC, leimeter-joaquin commented
Please, re qrite the name of the PR

2022-10-10 17:55 UTC, leimeter-joaquin requested changes
package-lock should not be changed. Run `npm i`, commit and check again.

2022-10-10 17:55 UTC, leimeter-joaquin commented on src/index.js
> +// const employees = require('./data/employees.json');
Remove this line if you are not using employees in this file.

2022-10-10 17:55 UTC, leimeter-joaquin commented on src/resources/employees.js
> +    const newEmployee = req.body;
You should probably not change any field that is not explicitly changed in the query. If I only want to change the email, I shouldn't have to send the name, lastName, phone...

2022-10-10 17:55 UTC, leimeter-joaquin commented on src/resources/employees.js
> +    res.status(201).json({ data: 'Deleted employee' });
This response should be sent in case fs.writeFile doesn't throw an error

2022-10-10 17:55 UTC, leimeter-joaquin commented on src/resources/employees.js
> +  if (req.query.id) {
You should check that the params sent by the user are correct.

2022-10-10 18:06 UTC, kolodani commented on src/index.js
> +// const employees = require('./data/employees.json');
line remove

2022-10-11 16:45 UTC, leimeter-joaquin approved these changes

2022-10-11 17:58 UTC, merged