BaSP-TG-W08: Projects Mateo
BaSP-a2022/lucas-a-trackgenix-server pull request #7
Opened 2022-10-10 16:27 UTC by matescarabino

2022-10-10 17:12 UTC, kolodani reviewed
el codigo esta espectacular, mate, no se si te siguen haciendo falta los comentarios antes de las funciones, los nombres son muy claros y se entiende por de mas el codigo

2022-10-10 18:06 UTC, leimeter-joaquin commented on src/resources/projects.js
> +    if ((req.body.isDeleted)) { (foundProject.isDeleted = req.body.isDeleted); }
You could

2022-10-10 18:34 UTC, leimeter-joaquin requested changes

2022-10-10 18:34 UTC, leimeter-joaquin commented on src/resources/projects.js
> +    // validar si employee ya esta asignado
Remove these comments in spanish or write them in english

2022-10-10 18:34 UTC, leimeter-joaquin commented on src/resources/projects.js
> +        },
Nice way to show errors

2022-10-11 18:24 UTC, leimeter-joaquin submitted a review, later dismissed

2022-10-11 18:33 UTC, kolodani approved these changes
its ok

2022-10-11 18:33 UTC, merged